[package]
name = "timescale"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.1.0", features = ["postgres", "64-column-tables", "chrono"] }
dotenvy = "0.15"
rand = "0.9.0-alpha.1"