// @generated automatically by Diesel CLI.

diesel::table! {
    speedy (time, serial_number) {
        time -> Timestamptz,
        serial_number -> Text,
        c00 -> Nullable<Float4>,
        c01 -> Nullable<Float4>,
        c02 -> Nullable<Float4>,
        c03 -> Nullable<Float4>,
        c04 -> Nullable<Float4>,
        c05 -> Nullable<Float4>,
        c06 -> Nullable<Float4>,
        c07 -> Nullable<Float4>,
        c08 -> Nullable<Float4>,
        c09 -> Nullable<Float4>,
        c10 -> Nullable<Float4>,
        c11 -> Nullable<Float4>,
        c12 -> Nullable<Float4>,
        c13 -> Nullable<Float4>,
        c14 -> Nullable<Float4>,
        c15 -> Nullable<Float4>,
        c16 -> Nullable<Float4>,
        c17 -> Nullable<Float4>,
        c18 -> Nullable<Float4>,
        c19 -> Nullable<Float4>,
        c20 -> Nullable<Float4>,
        c21 -> Nullable<Float4>,
        c22 -> Nullable<Float4>,
        c23 -> Nullable<Float4>,
        c24 -> Nullable<Float4>,
        c25 -> Nullable<Float4>,
        c26 -> Nullable<Float4>,
        c27 -> Nullable<Float4>,
        c28 -> Nullable<Float4>,
        c29 -> Nullable<Float4>,
        c30 -> Nullable<Float4>,
        c31 -> Nullable<Float4>,
        c32 -> Nullable<Float4>,
        c33 -> Nullable<Float4>,
        c34 -> Nullable<Float4>,
        c35 -> Nullable<Float4>,
        c36 -> Nullable<Float4>,
        c37 -> Nullable<Float4>,
        c38 -> Nullable<Float4>,
        c39 -> Nullable<Float4>,
        c40 -> Array<Nullable<Float4>>,
    }
}
